import { addDoc, doc, onSnapshot, orderBy, query, runTransaction, serverTimestamp } from 'firebase/firestore';
import { ArrowDownToLine, ArrowUpFromLine, CircleArrowDown, CircleArrowUp, CalendarClock, Trash2 } from 'lucide-react';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Modal } from '../components/Modal';
import { useToast } from '../components/Toast';
import { useAuth } from '../context/AuthContext';
import { db } from '../lib/firebase';
import { excluirContaPagar, excluirContaReceber } from '../lib/exclusoes';
import { empresaCollection, empresaDoc } from '../lib/tenant';
import { dataBr, hojeIso, moeda } from '../lib/utils';
import type { Cliente, ContaPagar, ContaReceber, OrdemServico } from '../types';

const contaReceberVazia = { clienteId: '', ordemServicoId: '', descricao: '', valorOriginal: 0, vencimento: hojeIso(), observacoes: '' };
const contaPagarVazia = { fornecedorNome: '', descricao: '', categoria: 'Despesa geral', valorOriginal: 0, vencimento: hojeIso(), observacoes: '' };

export function FinanceiroPage() {
  const [contasReceber, setContasReceber] = useState<ContaReceber[]>([]); const [contasPagar, setContasPagar] = useState<ContaPagar[]>([]); const [clientes, setClientes] = useState<Cliente[]>([]); const [ordens, setOrdens] = useState<OrdemServico[]>([]);
  const [tipoModal, setTipoModal] = useState<'RECEBER' | 'PAGAR' | null>(null); const [formReceber, setFormReceber] = useState(contaReceberVazia); const [formPagar, setFormPagar] = useState(contaPagarVazia); const [contaRecebimento, setContaRecebimento] = useState<ContaReceber | null>(null); const [contaPagamento, setContaPagamento] = useState<ContaPagar | null>(null); const [valorBaixa, setValorBaixa] = useState(0); const [formaPagamento, setFormaPagamento] = useState('DINHEIRO'); const [salvando, setSalvando] = useState(false); const [excluindoId, setExcluindoId] = useState<string | null>(null);
  const { usuario, empresaId } = useAuth(); const { showToast } = useToast(); const podeExcluir = usuario?.perfil === 'ADMIN';
  useEffect(() => onSnapshot(query(empresaCollection(empresaId!, 'contasReceber'), orderBy('vencimento', 'asc')), (snap) => setContasReceber(snap.docs.map((d) => ({ id: d.id, ...d.data() } as ContaReceber))), () => showToast('Não foi possível carregar contas a receber.', 'error')), [showToast, empresaId]);
  useEffect(() => onSnapshot(query(empresaCollection(empresaId!, 'contasPagar'), orderBy('vencimento', 'asc')), (snap) => setContasPagar(snap.docs.map((d) => ({ id: d.id, ...d.data() } as ContaPagar))), () => showToast('Não foi possível carregar contas a pagar.', 'error')), [showToast, empresaId]);
  useEffect(() => onSnapshot(query(empresaCollection(empresaId!, 'clientes'), orderBy('nome')), (snap) => setClientes(snap.docs.map((d) => ({ id: d.id, ...d.data() } as Cliente))), () => undefined), [empresaId]);
  useEffect(() => onSnapshot(query(empresaCollection(empresaId!, 'ordensServico'), orderBy('criadoEm', 'desc')), (snap) => setOrdens(snap.docs.map((d) => ({ id: d.id, ...d.data() } as OrdemServico))), () => undefined), [empresaId]);

  const totalReceber = useMemo(() => contasReceber.filter((conta) => ['ABERTA', 'PARCIAL'].includes(conta.status)).reduce((soma, conta) => soma + Number(conta.valorAberto || 0), 0), [contasReceber]);
  const totalPagar = useMemo(() => contasPagar.filter((conta) => ['ABERTA', 'PARCIAL'].includes(conta.status)).reduce((soma, conta) => soma + Number(conta.valorAberto || 0), 0), [contasPagar]);
  const clienteDaConta = clientes.find((cliente) => cliente.id === formReceber.clienteId);

  const abrirContaReceber = () => { setFormReceber(contaReceberVazia); setTipoModal('RECEBER'); };
  const abrirContaPagar = () => { setFormPagar(contaPagarVazia); setTipoModal('PAGAR'); };
  const selecionarOS = (id: string) => { const os = ordens.find((ordem) => ordem.id === id); setFormReceber((atual) => ({ ...atual, ordemServicoId: id, clienteId: os?.clienteId ?? atual.clienteId, descricao: os ? `OS #${String(os.numero).padStart(5, '0')} — ${os.aparelhoMarca} ${os.aparelhoModelo}` : atual.descricao, valorOriginal: os ? Math.max(0, os.valorTotal) : atual.valorOriginal })); };

  const salvarContaReceber = async (evento: FormEvent) => { evento.preventDefault(); if (!clienteDaConta) return showToast('Selecione um cliente.', 'error'); setSalvando(true); try { const os = ordens.find((ordem) => ordem.id === formReceber.ordemServicoId); await addDoc(empresaCollection(empresaId!, 'contasReceber'), { clienteId: clienteDaConta.id, clienteNome: clienteDaConta.nome, ordemServicoId: os?.id ?? '', ordemServicoNumero: os?.numero ?? null, descricao: formReceber.descricao.trim(), valorOriginal: Number(formReceber.valorOriginal), valorAberto: Number(formReceber.valorOriginal), vencimento: formReceber.vencimento, status: 'ABERTA', observacoes: formReceber.observacoes.trim(), criadoEm: serverTimestamp(), atualizadoEm: serverTimestamp() }); showToast('Conta a receber lançada.'); setTipoModal(null); } catch { showToast('Não foi possível lançar a conta a receber.', 'error'); } finally { setSalvando(false); } };
  const salvarContaPagar = async (evento: FormEvent) => { evento.preventDefault(); setSalvando(true); try { await addDoc(empresaCollection(empresaId!, 'contasPagar'), { fornecedorNome: formPagar.fornecedorNome.trim(), descricao: formPagar.descricao.trim(), categoria: formPagar.categoria.trim(), valorOriginal: Number(formPagar.valorOriginal), valorAberto: Number(formPagar.valorOriginal), vencimento: formPagar.vencimento, status: 'ABERTA', observacoes: formPagar.observacoes.trim(), criadoEm: serverTimestamp(), atualizadoEm: serverTimestamp() }); showToast('Conta a pagar lançada.'); setTipoModal(null); } catch { showToast('Não foi possível lançar a conta a pagar.', 'error'); } finally { setSalvando(false); } };

  const abrirRecebimento = (conta: ContaReceber) => { setContaRecebimento(conta); setValorBaixa(conta.valorAberto); setFormaPagamento('DINHEIRO'); };
  const abrirPagamento = (conta: ContaPagar) => { setContaPagamento(conta); setValorBaixa(conta.valorAberto); setFormaPagamento('PIX'); };
  const confirmarRecebimento = async () => { if (!contaRecebimento || !usuario) return; if (valorBaixa <= 0 || valorBaixa > contaRecebimento.valorAberto) return showToast('Informe um valor entre zero e o saldo em aberto.', 'error'); setSalvando(true); try { await runTransaction(db, async (transaction) => { const contaRef = empresaDoc(empresaId!, 'contasReceber', contaRecebimento.id); const snap = await transaction.get(contaRef); if (!snap.exists()) throw new Error('Conta não encontrada.'); const atual = snap.data() as ContaReceber; const saldo = Math.max(0, Number(atual.valorAberto) - Number(valorBaixa)); transaction.update(contaRef, { valorAberto: saldo, status: saldo === 0 ? 'RECEBIDA' : 'PARCIAL', atualizadoEm: serverTimestamp() }); const registroFinanceiroId = (atual as ContaReceber & { registroFinanceiroId?: string }).registroFinanceiroId; if (registroFinanceiroId) transaction.update(empresaDoc(empresaId!, 'registrosFinanceiros', registroFinanceiroId), { status: saldo === 0 ? 'RECEBIDO' : 'PARCIAL', valorAberto: saldo, atualizadoEm: serverTimestamp() }); transaction.set(doc(empresaCollection(empresaId!, 'recebimentos')), { contaReceberId: contaRecebimento.id, clienteNome: atual.clienteNome, valor: Number(valorBaixa), data: hojeIso(), formaPagamento, usuarioId: usuario.id, usuarioNome: usuario.nome, criadoEm: serverTimestamp() }); transaction.set(doc(empresaCollection(empresaId!, 'movimentacoesCaixa')), { tipo: 'ENTRADA', origem: 'RECEBIMENTO', origemId: contaRecebimento.id, descricao: `Recebimento — ${atual.descricao}`, clienteId: atual.clienteId || '', clienteNome: atual.clienteNome, valor: Number(valorBaixa), formaPagamento, data: hojeIso(), usuarioId: usuario.id, usuarioNome: usuario.nome, criadoEm: serverTimestamp() }); }); showToast('Recebimento registrado.'); setContaRecebimento(null); } catch (error) { showToast(error instanceof Error ? error.message : 'Não foi possível registrar o recebimento.', 'error'); } finally { setSalvando(false); } };
  const confirmarPagamento = async () => { if (!contaPagamento || !usuario) return; if (valorBaixa <= 0 || valorBaixa > contaPagamento.valorAberto) return showToast('Informe um valor entre zero e o saldo em aberto.', 'error'); setSalvando(true); try { await runTransaction(db, async (transaction) => { const contaRef = empresaDoc(empresaId!, 'contasPagar', contaPagamento.id); const snap = await transaction.get(contaRef); if (!snap.exists()) throw new Error('Conta não encontrada.'); const atual = snap.data() as ContaPagar; const saldo = Math.max(0, Number(atual.valorAberto) - Number(valorBaixa)); transaction.update(contaRef, { valorAberto: saldo, status: saldo === 0 ? 'PAGA' : 'PARCIAL', atualizadoEm: serverTimestamp() }); transaction.set(doc(empresaCollection(empresaId!, 'pagamentos')), { contaPagarId: contaPagamento.id, fornecedorNome: atual.fornecedorNome, valor: Number(valorBaixa), data: hojeIso(), formaPagamento, usuarioId: usuario.id, usuarioNome: usuario.nome, criadoEm: serverTimestamp() }); transaction.set(doc(empresaCollection(empresaId!, 'movimentacoesCaixa')), { tipo: 'SAIDA', origem: 'PAGAMENTO', origemId: contaPagamento.id, descricao: `Pagamento — ${atual.descricao}`, clienteNome: atual.fornecedorNome, valor: Number(valorBaixa), formaPagamento, data: hojeIso(), usuarioId: usuario.id, usuarioNome: usuario.nome, criadoEm: serverTimestamp() }); }); showToast('Pagamento registrado.'); setContaPagamento(null); } catch (error) { showToast(error instanceof Error ? error.message : 'Não foi possível registrar o pagamento.', 'error'); } finally { setSalvando(false); } };

  const excluirReceber = async (conta: ContaReceber) => {
    if (!podeExcluir) return showToast('Somente administradores podem excluir contas a receber.', 'error');
    if (!window.confirm(`Excluir definitivamente a conta a receber de “${conta.clienteNome}” no valor de ${moeda(conta.valorOriginal)}?

Recebimentos, movimentações de caixa e registros financeiros vinculados também serão removidos.`)) return;
    setExcluindoId(`receber-${conta.id}`);
    try {
      await excluirContaReceber(empresaId!, conta);
      showToast('Conta a receber excluída.');
    } catch (error) {
      showToast(error instanceof Error ? error.message : 'Não foi possível excluir a conta a receber.', 'error');
    } finally {
      setExcluindoId(null);
    }
  };

  const excluirPagar = async (conta: ContaPagar) => {
    if (!podeExcluir) return showToast('Somente administradores podem excluir contas a pagar.', 'error');
    if (!window.confirm(`Excluir definitivamente a conta a pagar de “${conta.fornecedorNome}” no valor de ${moeda(conta.valorOriginal)}?

Pagamentos e movimentações de caixa vinculados também serão removidos.`)) return;
    setExcluindoId(`pagar-${conta.id}`);
    try {
      await excluirContaPagar(empresaId!, conta);
      showToast('Conta a pagar excluída.');
    } catch (error) {
      showToast(error instanceof Error ? error.message : 'Não foi possível excluir a conta a pagar.', 'error');
    } finally {
      setExcluindoId(null);
    }
  };


  return <>
    <section className="page-heading"><div><p className="eyebrow">FINANCEIRO</p><h2>Contas e baixas</h2><p>Controle valores a receber, contas a pagar e pagamentos realizados.</p></div><div className="button-group"><button className="button button-secondary" onClick={abrirContaPagar}><ArrowUpFromLine size={18} />Lançar conta a pagar</button><button className="button button-primary" onClick={abrirContaReceber}><ArrowDownToLine size={18} />Lançar conta a receber</button></div></section>
    <div className="stats-grid"><article className="stat-card"><div className="stat-icon teal"><CircleArrowDown size={21} /></div><div><span>Total a receber</span><strong className="currency-stat">{moeda(totalReceber)}</strong></div></article><article className="stat-card"><div className="stat-icon rose"><CircleArrowUp size={21} /></div><div><span>Total a pagar</span><strong className="currency-stat">{moeda(totalPagar)}</strong></div></article><article className="stat-card"><div className="stat-icon amber"><CalendarClock size={21} /></div><div><span>Contas a receber abertas</span><strong>{contasReceber.filter((c) => ['ABERTA', 'PARCIAL'].includes(c.status)).length}</strong></div></article><article className="stat-card"><div className="stat-icon blue"><CalendarClock size={21} /></div><div><span>Contas a pagar abertas</span><strong>{contasPagar.filter((c) => ['ABERTA', 'PARCIAL'].includes(c.status)).length}</strong></div></article></div>
    <div className="dashboard-columns finance-columns"><section className="panel"><div className="panel-header"><div><h3>Contas a receber</h3><p>Clientes e vendas pendentes</p></div></div><div className="table-wrap compact-table"><table><thead><tr><th>Cliente / descrição</th><th>Vencimento</th><th>Saldo</th><th>Status</th><th>Ações</th></tr></thead><tbody>{contasReceber.map((conta) => <tr key={conta.id}><td><strong>{conta.clienteNome}</strong><small>{conta.descricao}</small></td><td>{dataBr(conta.vencimento)}</td><td>{moeda(conta.valorAberto)}</td><td><span className={`badge ${conta.status === 'RECEBIDA' ? 'badge-success' : conta.status === 'PARCIAL' ? 'badge-warning' : 'badge-muted'}`}>{conta.status}</span></td><td className="actions-cell">{['ABERTA', 'PARCIAL'].includes(conta.status) && <button className="button button-small" onClick={() => abrirRecebimento(conta)}>Receber</button>}{podeExcluir && <button className="icon-button danger" title="Excluir conta a receber" disabled={excluindoId === `receber-${conta.id}`} onClick={() => void excluirReceber(conta)}><Trash2 size={17}/></button>}</td></tr>)}{contasReceber.length === 0 && <tr><td colSpan={5}><div className="empty-state compact">Nenhuma conta a receber.</div></td></tr>}</tbody></table></div></section>
      <section className="panel"><div className="panel-header"><div><h3>Contas a pagar</h3><p>Fornecedores e despesas da loja</p></div></div><div className="table-wrap compact-table"><table><thead><tr><th>Fornecedor / descrição</th><th>Vencimento</th><th>Saldo</th><th>Status</th><th>Ações</th></tr></thead><tbody>{contasPagar.map((conta) => <tr key={conta.id}><td><strong>{conta.fornecedorNome}</strong><small>{conta.descricao}</small></td><td>{dataBr(conta.vencimento)}</td><td>{moeda(conta.valorAberto)}</td><td><span className={`badge ${conta.status === 'PAGA' ? 'badge-success' : conta.status === 'PARCIAL' ? 'badge-warning' : 'badge-muted'}`}>{conta.status}</span></td><td className="actions-cell">{['ABERTA', 'PARCIAL'].includes(conta.status) && <button className="button button-small" onClick={() => abrirPagamento(conta)}>Pagar</button>}{podeExcluir && <button className="icon-button danger" title="Excluir conta a pagar" disabled={excluindoId === `pagar-${conta.id}`} onClick={() => void excluirPagar(conta)}><Trash2 size={17}/></button>}</td></tr>)}{contasPagar.length === 0 && <tr><td colSpan={5}><div className="empty-state compact">Nenhuma conta a pagar.</div></td></tr>}</tbody></table></div></section></div>
    <Modal aberto={tipoModal === 'RECEBER'} aoFechar={() => setTipoModal(null)} titulo="Nova conta a receber"><form className="form-grid" onSubmit={salvarContaReceber}><label className="field field-full"><span>Vincular a uma OS (opcional)</span><select value={formReceber.ordemServicoId} onChange={(e) => selecionarOS(e.target.value)}><option value="">Não vincular</option>{ordens.map((os) => <option key={os.id} value={os.id}>OS #{String(os.numero).padStart(5, '0')} — {os.clienteNome} — {moeda(os.valorTotal)}</option>)}</select></label><label className="field field-full"><span>Cliente *</span><select required value={formReceber.clienteId} onChange={(e) => setFormReceber({ ...formReceber, clienteId: e.target.value })}><option value="">Selecione</option>{clientes.filter((c) => c.ativo).map((cliente) => <option key={cliente.id} value={cliente.id}>{cliente.nome}</option>)}</select></label><label className="field field-full"><span>Descrição *</span><input required value={formReceber.descricao} onChange={(e) => setFormReceber({ ...formReceber, descricao: e.target.value })} /></label><label className="field"><span>Valor *</span><input required min="0.01" step="0.01" type="number" value={formReceber.valorOriginal} onChange={(e) => setFormReceber({ ...formReceber, valorOriginal: Number(e.target.value || 0) })} /></label><label className="field"><span>Vencimento *</span><input required type="date" value={formReceber.vencimento} onChange={(e) => setFormReceber({ ...formReceber, vencimento: e.target.value })} /></label><label className="field field-full"><span>Observações</span><textarea rows={2} value={formReceber.observacoes} onChange={(e) => setFormReceber({ ...formReceber, observacoes: e.target.value })} /></label><div className="modal-actions field-full"><button type="button" className="button button-secondary" onClick={() => setTipoModal(null)}>Cancelar</button><button className="button button-primary" disabled={salvando}>{salvando ? 'Salvando...' : 'Lançar conta'}</button></div></form></Modal>
    <Modal aberto={tipoModal === 'PAGAR'} aoFechar={() => setTipoModal(null)} titulo="Nova conta a pagar"><form className="form-grid" onSubmit={salvarContaPagar}><label className="field field-full"><span>Fornecedor *</span><input required value={formPagar.fornecedorNome} onChange={(e) => setFormPagar({ ...formPagar, fornecedorNome: e.target.value })} /></label><label className="field field-full"><span>Descrição *</span><input required value={formPagar.descricao} onChange={(e) => setFormPagar({ ...formPagar, descricao: e.target.value })} /></label><label className="field"><span>Categoria</span><input value={formPagar.categoria} onChange={(e) => setFormPagar({ ...formPagar, categoria: e.target.value })} /></label><label className="field"><span>Valor *</span><input required min="0.01" step="0.01" type="number" value={formPagar.valorOriginal} onChange={(e) => setFormPagar({ ...formPagar, valorOriginal: Number(e.target.value || 0) })} /></label><label className="field"><span>Vencimento *</span><input required type="date" value={formPagar.vencimento} onChange={(e) => setFormPagar({ ...formPagar, vencimento: e.target.value })} /></label><label className="field field-full"><span>Observações</span><textarea rows={2} value={formPagar.observacoes} onChange={(e) => setFormPagar({ ...formPagar, observacoes: e.target.value })} /></label><div className="modal-actions field-full"><button type="button" className="button button-secondary" onClick={() => setTipoModal(null)}>Cancelar</button><button className="button button-primary" disabled={salvando}>{salvando ? 'Salvando...' : 'Lançar conta'}</button></div></form></Modal>
    <Modal aberto={!!contaRecebimento} aoFechar={() => setContaRecebimento(null)} titulo="Registrar recebimento"><div className="form-stack"><div className="info-box">Cliente: <strong>{contaRecebimento?.clienteNome}</strong><br />Saldo em aberto: <strong>{moeda(contaRecebimento?.valorAberto)}</strong></div><label className="field"><span>Valor recebido</span><input type="number" min="0.01" max={contaRecebimento?.valorAberto} step="0.01" value={valorBaixa} onChange={(e) => setValorBaixa(Number(e.target.value || 0))} /></label><label className="field"><span>Forma de pagamento</span><select value={formaPagamento} onChange={(e) => setFormaPagamento(e.target.value)}><option>DINHEIRO</option><option>PIX</option><option>CARTÃO</option><option>TRANSFERÊNCIA</option><option>BOLETO</option></select></label><div className="modal-actions"><button className="button button-secondary" onClick={() => setContaRecebimento(null)}>Cancelar</button><button className="button button-primary" disabled={salvando} onClick={() => void confirmarRecebimento()}>{salvando ? 'Registrando...' : 'Confirmar recebimento'}</button></div></div></Modal>
    <Modal aberto={!!contaPagamento} aoFechar={() => setContaPagamento(null)} titulo="Registrar pagamento"><div className="form-stack"><div className="info-box">Fornecedor: <strong>{contaPagamento?.fornecedorNome}</strong><br />Saldo em aberto: <strong>{moeda(contaPagamento?.valorAberto)}</strong></div><label className="field"><span>Valor pago</span><input type="number" min="0.01" max={contaPagamento?.valorAberto} step="0.01" value={valorBaixa} onChange={(e) => setValorBaixa(Number(e.target.value || 0))} /></label><label className="field"><span>Forma de pagamento</span><select value={formaPagamento} onChange={(e) => setFormaPagamento(e.target.value)}><option>PIX</option><option>DINHEIRO</option><option>TRANSFERÊNCIA</option><option>CARTÃO</option><option>BOLETO</option></select></label><div className="modal-actions"><button className="button button-secondary" onClick={() => setContaPagamento(null)}>Cancelar</button><button className="button button-primary" disabled={salvando} onClick={() => void confirmarPagamento()}>{salvando ? 'Registrando...' : 'Confirmar pagamento'}</button></div></div></Modal>
  </>;
}
